services:
  postgres:
    image: postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    ports:
      - 5433:5432
  bot:
    build: .
    restart: unless-stopped
    volumes:
      - ./bot:/bot
      - ./bot.yml:/etc/bot/bot.yml
    env_file:
      - .env
    command:
      - "--config=/etc/bot/bot.yml"
    tty: true
    depends_on:
      - postgres

