name: Build and push image

on:
  push:
    branches:
      - 'main'
      - "*"
    tags:
      - "v*.*.*"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    permissions:
      contents: read
      packages: write
      attestations: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # calculate the short sha for the latest commit
      - name: Set commit sha_short
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

        # the latest tag is only applied for the main branch and git tags
      - name: Determine latest tag
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/main" || "${GITHUB_REF}" == refs/tags/v*.*.* ]]; then
            echo "LATEST_TAG=ghcr.io/${{ github.repository }}:latest" >> $GITHUB_ENV
          else
            echo "LATEST_TAG=" >> $GITHUB_ENV
          fi

        # Setup QEMU to support x86 and ARM builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push the image
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          # update the latest tag only if this is the main branch or this is a tag
          tags: |
            ${{ env.LATEST_TAG }}
            ghcr.io/mohammedgqudah/kube-inspector-bot:${{ env.sha_short }}
            ghcr.io/mohammedgqudah/kube-inspector-bot:${{ github.ref_name }}

