name: Build and push image

on:
  push:
    branches:
      - 'main'
      - "*"
    tags:
      - "v*.*.*"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    permissions:
      contents: read
      packages: write
      attestations: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # calculate the short sha for the latest commit
      - name: Set commit sha_short
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push the image
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          # update the latest tag only if this is the main branch or this is a tag
          tags: |
            ${{ (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')) ? format('ghcr.io/{0}:latest', github.repository) : '' }}
            ghcr.io/mohammedgqudah/d5dk8s:${{ env.sha_short }}
            ghcr.io/mohammedgqudah/d5dk8s:${{ github.ref_name }}
